/**
 * Branded HTML email templates. Plain inline-styled HTML (email clients ignore
 * <style> and external CSS), kept deliberately simple so it renders the same in
 * Gmail, Apple Mail, and Outlook. Voice matches the house style: no em dashes,
 * complete sentences, no hype.
 *
 * REBUILT ON THE BRAND, August 26, 2026. These templates had been left behind by
 * the August 2026 newspaper pass and were still shipping the retired system:
 * indigo `#4f46e5` accents, 16px rounded cards, 10px rounded buttons, a grey
 * `#f4f4f6` app-shell background, and a sans-serif reading surface. The site had
 * moved to oxblood, square corners, paper stock, and a serif reading surface
 * weeks earlier, so a subscriber who clicked through from a broadcast watched the
 * brand change under them. Every colour, rule, and typeface now comes from
 * `lib/brand.ts`, which mirrors globals.css, so the next palette change moves both
 * surfaces at once instead of only the one somebody remembered.
 *
 * THE EDITORIAL SPLIT APPLIES HERE TOO, and it matters most in a broadcast,
 * because a broadcast is the whole article. Serif carries the nameplate, the
 * headline, the standfirst, and the body. Sans is chrome only: the eyebrow, the
 * buttons, the footer, the lead-notification table.
 */
import { site } from "@/lib/site";
import {
  ACCENT,
  INK,
  INK_MUTED,
  INK_SOFT,
  PAPER,
  RULE,
  RULE_STRONG,
  SANS,
  SERIF,
  SURFACE,
} from "@/lib/brand";

/**
 * The postal address CAN-SPAM requires on commercial email. Read from the
 * environment so it can be set without a deploy and so no placeholder ever
 * ships as a real address. When it is unset the line is simply omitted, which
 * is the honest failure mode, but note that sending commercial mail without it
 * is the one compliance gap in this file. Use a PO box, not a home address.
 */
const POSTAL_ADDRESS = process.env.EMAIL_POSTAL_ADDRESS ?? "";

/** The hosted mark, generated by `scripts/brand/make-email-mark.mjs`. Absolute,
 *  because a mail client has no page origin to resolve a relative path against. */
const MARK_URL = `${site.url}/email/mark.png`;

/** Bare host for footer prose. `site.url` carries the protocol and the www, and
 *  neither belongs in a sentence a person reads. */
function hostOf(url: string): string {
  return url.replace(/^https?:\/\//, "").replace(/^www\./, "");
}

/**
 * The owned-list footer. Wording is deliberately true for BOTH intake paths:
 * someone who used the on-site form and someone Alex added by hand after they
 * said yes on a call. The old text claimed "you subscribed at alexprompts.com",
 * which is false for a manual add and is the fastest way to earn a spam
 * complaint from a contact who does not remember a form.
 */
function listFooter(unsubUrl: string): string {
  return `You are getting this because you asked to be on the ${site.name} list.<br />
     <a href="${unsubUrl}" style="color:${INK_MUTED};text-decoration:underline;">Unsubscribe</a>${
       POSTAL_ADDRESS ? `<br /><span style="color:${INK_MUTED};">${POSTAL_ADDRESS}</span>` : ""
     }`;
}

/**
 * THE NAMEPLATE. A newspaper masthead, not a SaaS logo bar: the mark, the name
 * set in the brand serif at real size, an oxblood rule, and the beat underneath.
 * It replaces a 13px uppercase indigo label that read as a transactional
 * notification from a software company.
 *
 * It is built as a table with the mark and the name in SEPARATE cells rather
 * than as one lockup image, because images are off by default in Outlook and for
 * any sender the reader has not whitelisted. With images blocked this still
 * renders the name and the beat in live type and loses nothing but the cup. A
 * logo shipped as a single PNG would render as an empty box, which is the most
 * common way a good-looking email template fails in the real world.
 *
 * The tagline is read from `site.ts`, so the beat the inbox advertises cannot
 * drift from the beat the site advertises. That exact drift is what left the
 * subscribe page promising three retired tracks for a week.
 */
function nameplate(): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse:collapse;">
      <tr>
        <td width="40" valign="middle" style="padding:0 10px 0 0;">
          <img src="${MARK_URL}" width="30" height="30" alt="" style="display:block;width:30px;height:30px;border:0;" />
        </td>
        <td valign="middle" style="font-family:${SERIF};font-size:26px;font-weight:700;letter-spacing:-0.01em;color:${INK};line-height:1.1;">${site.name}</td>
      </tr>
    </table>
    <div style="border-top:2px solid ${ACCENT};font-size:0;line-height:0;margin:12px 0 0;">&nbsp;</div>
    <div style="font-family:${SANS};font-size:11px;font-weight:700;letter-spacing:0.13em;text-transform:uppercase;color:${ACCENT};padding:9px 0 0;">${site.tagline}</div>`;
}

/** Shared shell: a squared card on paper stock, the nameplate, the body, and a
 *  footer. `footer` carries the unsubscribe / physical-address line (CAN-SPAM).
 *  `maxWidth` widens the card for full-article sends; a 520px column is right
 *  for a short notification but too narrow to read 1,200 words in.
 *
 *  No border-radius anywhere, and no drop shadow. Both were in the old version
 *  and both are the app-shell tells the newspaper pass stripped out of the site:
 *  here as there, rules do the separating that a card shadow used to. */
function shell(bodyHtml: string, footer: string, maxWidth = 520): string {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8" /><meta name="viewport" content="width=device-width,initial-scale=1" /></head>
<body style="margin:0;padding:0;background:${PAPER};font-family:${SANS};">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${PAPER};padding:32px 16px;">
    <tr><td align="center">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:${maxWidth}px;background:${SURFACE};border:1px solid ${RULE_STRONG};">
        <tr><td style="padding:30px 36px 0;">
          ${nameplate()}
        </td></tr>
        <tr><td style="padding:26px 36px 32px;color:${INK};font-size:16px;line-height:1.6;">
          ${bodyHtml}
        </td></tr>
      </table>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:${maxWidth}px;">
        <tr><td style="padding:18px 36px;font-family:${SANS};color:${INK_MUTED};font-size:12px;line-height:1.6;text-align:center;">
          ${footer}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

/** A button: a flat block of oxblood with square corners, matching
 *  `.theme-cta-accent` on the site. The old one was indigo with a 10px radius. */
function btn(href: string, label: string): string {
  return `<a href="${href}" style="display:inline-block;background:${ACCENT};color:#ffffff;text-decoration:none;font-family:${SANS};font-weight:600;font-size:14px;letter-spacing:0.01em;padding:13px 26px;">${label}</a>`;
}

/** A headline, set in the brand serif so a confirmation and a broadcast open the
 *  same way the site's pages do. */
function headline(text: string, size = 26): string {
  return `<h1 style="font-family:${SERIF};font-size:${size}px;font-weight:700;margin:0 0 14px;color:${INK};line-height:1.22;letter-spacing:-0.012em;">${text}</h1>`;
}

/** A standfirst: the summary line under a headline, serif and softened ink,
 *  matching `type-body-lg` + `theme-text-secondary` on the site. */
function standfirst(text: string, size = 17): string {
  return `<p style="margin:0 0 22px;font-family:${SERIF};font-size:${size}px;line-height:1.55;color:${INK_SOFT};">${text}</p>`;
}

/** Double opt-in confirmation email. */
export function confirmEmail(confirmUrl: string): { subject: string; html: string; text: string } {
  const subject = `Confirm your subscription to ${site.name}`;
  const html = shell(
    `${headline("Confirm your email", 24)}
     ${standfirst("Tap the button and you are on the list. If you did not ask for this, ignore this email and nothing will be sent.")}
     <p style="margin:0 0 26px;">${btn(confirmUrl, "Confirm my email")}</p>
     <p style="margin:0;font-family:${SANS};color:${INK_MUTED};font-size:13px;line-height:1.6;">Or paste this link into your browser:<br /><a href="${confirmUrl}" style="color:${ACCENT};word-break:break-all;">${confirmUrl}</a></p>`,
    `Someone entered this address at ${hostOf(site.url)}.`,
  );
  const text = `Confirm your subscription to ${site.name} by opening this link: ${confirmUrl}\n\nIf you did not request this, ignore this email.`;
  return { subject, html, text };
}

/**
 * The buy/sell line, in the inbox. ONE QUIET LINE as of August 26, 2026, kept
 * verbatim in sync with `ReferralCta` on the site (Alex: "the cta should just be
 * subtle"). It was a bordered grey panel with a heading, a paragraph, and a
 * filled button, which is a lot of chrome to put under an article somebody is
 * already reading in full.
 *
 * Set in the serif, because it sits at the foot of the reading column and a sans
 * line there reads as an ad slot rather than as the writer still talking.
 */
function referralBlock(referralUrl: string): string {
  return `<p style="margin:26px 0 4px;padding-top:18px;border-top:1px solid ${RULE};font-family:${SERIF};font-size:17px;line-height:1.6;">
      <a href="${referralUrl}" style="color:${ACCENT};text-decoration:underline;font-weight:700;">Buying or Selling? Let&rsquo;s talk.</a>
    </p>`;
}

/**
 * A broadcast email for a published site post.
 *
 * Two shapes. When `bodyHtml` is supplied the FULL article ships in the email
 * (the Morning Brew model): the reader gets the whole thing in the inbox and the
 * site link becomes a convenience for forwarding rather than a toll gate. This
 * is the right default for a list of sphere professionals, where a click-through
 * is friction on a five-minute read and the habit is the whole point. Without
 * `bodyHtml` it falls back to the original title-plus-summary notification, so
 * any caller that has no body still works.
 */
export function postBroadcastEmail(opts: {
  title: string;
  summary: string | null;
  postUrl: string;
  unsubUrl: string;
  /** Inline-styled article HTML from `renderEmailBody`. Omit for the teaser. */
  bodyHtml?: string | null;
  /** Raw markdown, used verbatim for the text/plain part (markdown reads fine). */
  bodyMd?: string | null;
  /** When set, append the referral offer. Mirrors the site's per-section flag. */
  referralUrl?: string | null;
}): { subject: string; html: string; text: string } {
  const { title, summary, postUrl, unsubUrl, bodyHtml, bodyMd, referralUrl } = opts;
  const subject = title;

  if (!bodyHtml) {
    const html = shell(
      `${headline(escapeHtml(title), 24)}
       ${summary ? standfirst(escapeHtml(summary)) : ""}
       <p style="margin:0 0 8px;">${btn(postUrl, "Read it")}</p>`,
      listFooter(unsubUrl),
    );
    const text = `${title}\n\n${summary ?? ""}\n\nRead it: ${postUrl}\n\nUnsubscribe: ${unsubUrl}`;
    return { subject, html, text };
  }

  const html = shell(
    `${headline(escapeHtml(title), 28)}
     ${summary ? standfirst(escapeHtml(summary), 18) : ""}
     <p style="margin:0 0 22px;font-family:${SANS};font-size:12px;letter-spacing:0.02em;color:${INK_MUTED};">
       <a href="${postUrl}" style="color:${INK_MUTED};text-decoration:underline;">View this on the site</a>
     </p>
     <hr style="border:0;border-top:1px solid ${RULE_STRONG};margin:0 0 24px;" />
     ${bodyHtml}
     ${referralUrl ? referralBlock(referralUrl) : ""}
     <p style="margin:22px 0 0;font-family:${SANS};font-size:13px;">
       <a href="${postUrl}" style="color:${ACCENT};text-decoration:underline;font-weight:600;">Read it on the site</a>
     </p>`,
    listFooter(unsubUrl),
    600,
  );

  // Markdown is already readable as plain text, so it is the text/plain part
  // verbatim. A stripped-tags conversion would only lose the link targets.
  const text = `${title}\n\n${summary ? `${summary}\n\n` : ""}${bodyMd ?? ""}\n\nRead it on the site: ${postUrl}\n\nUnsubscribe: ${unsubUrl}`;
  return { subject, html, text };
}

/** Internal notification to Alex when a lead arrives, from the form or the booking page.
 *  This goes to Alex, not the lead, so it is plain and information-dense: it leads
 *  with the qualifying details so he can follow up warm within a day.
 *
 *  The table is set in SANS throughout, deliberately breaking the editorial split.
 *  It is not a reading surface, it is a record, and the site sets its tables and
 *  labels in sans for exactly the same reason.
 *
 *  TWO KINDS OF LEAD, ONE TEMPLATE (August 29, 2026). `kind: "booking"` is a call
 *  somebody scheduled on the booking page, arriving through the Cal.com webhook
 *  at /api/booking rather than through a form. It gets its own subject line and
 *  its own opening sentence, because the two need opposite things from Alex: a
 *  form lead needs a reply while it is warm, and a booked call is already on his
 *  calendar and needs him to show up for it. Telling him "someone filled out the
 *  form" about a call at 2pm tomorrow would be actively misleading, which is why
 *  this branches rather than shipping a second near-copy of the template. */
export function leadNotifyEmail(lead: {
  name: string | null;
  email: string;
  phone: string | null;
  intent: string | null;
  location: string | null;
  movingFrom: string | null;
  timeframe: string | null;
  message: string | null;
  refSlug?: string | null;
  referrer?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  smsConsent?: boolean;
  /** "booking" when this arrived from the scheduler webhook rather than a form. */
  kind?: "form" | "booking";
  /** The scheduled call time, already formatted in Alex's timezone. */
  when?: string | null;
}): { subject: string; html: string; text: string } {
  const who = lead.name?.trim() || lead.email;
  const booking = lead.kind === "booking";
  // The subject line is the entire notification for anyone reading it on a phone
  // lock screen, so it has to say which of the two things happened.
  const subject = booking ? `Call booked: ${who}` : `New lead: ${who}`;

  const rows: Array<[string, string | null]> = [
    // First on purpose. When the call is already scheduled, the time is the one
    // thing Alex has to act on.
    ["Call time", booking ? (lead.when ?? null) : null],
    ["Name", lead.name],
    ["Email", lead.email],
    ["Phone", lead.phone],
    // Spelled out rather than left blank, because the expensive mistake here is
    // texting someone who never agreed. A number with no consent gets a loud
    // row saying so; a lead with no number at all gets nothing.
    [
      "Texting",
      lead.phone ? (lead.smsConsent ? "Consented, OK to text" : "NO consent, do not text") : null,
    ],
    ["Looking to", prettyIntent(lead.intent)],
    ["Market", lead.location],
    ["Moving from", lead.movingFrom],
    ["Timeframe", prettyTimeframe(lead.timeframe)],
    ["Notes", lead.message],
    ["Came from", leadSource(lead)],
  ];

  const rowsHtml = rows
    .filter(([, v]) => v && v.trim())
    .map(
      ([label, v]) =>
        `<tr>
           <td style="padding:8px 14px 8px 0;font-family:${SANS};color:${INK_MUTED};font-size:11px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;white-space:nowrap;vertical-align:top;border-bottom:1px solid ${RULE};">${label}</td>
           <td style="padding:8px 0;font-family:${SANS};color:${INK};font-size:14px;line-height:1.5;vertical-align:top;border-bottom:1px solid ${RULE};">${escapeHtml(v as string)}</td>
         </tr>`,
    )
    .join("");

  const html = shell(
    `${headline(booking ? "Call booked" : "New lead", 24)}
     <p style="margin:0 0 20px;font-family:${SANS};font-size:14px;line-height:1.6;color:${INK_MUTED};">${
       booking
         ? "Somebody booked a call with you. It is on your calendar already, and what they gave the booking form is below."
         : "Someone filled out the form. Reach out while it is warm."
     }</p>
     <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="width:100%;border-collapse:collapse;border-top:1px solid ${RULE_STRONG};">${rowsHtml}</table>
     <p style="margin:24px 0 0;">${btn(`mailto:${escapeHtml(lead.email)}`, booking ? "Email them before the call" : "Reply to this lead")}</p>`,
    booking
      ? `Booked through the scheduling page linked from ${hostOf(site.url)}.`
      : `Sent from the form at ${hostOf(site.url)}/buying-or-selling.`,
  );

  const text = rows
    .filter(([, v]) => v && v.trim())
    .map(([label, v]) => `${label}: ${v}`)
    .join("\n");

  return { subject, html, text: `${booking ? "Call booked" : "New lead"}\n\n${text}` };
}

/** A human one-line "where did this lead come from" for the notification, from the
 *  first-party attribution. Prefers the article that drove it, then a campaign tag,
 *  then the raw referrer. */
function leadSource(lead: {
  refSlug?: string | null;
  referrer?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
}): string | null {
  if (lead.refSlug?.trim()) return `Article: ${lead.refSlug.trim()}`;
  const utm = [lead.utmSource, lead.utmMedium, lead.utmCampaign].filter(Boolean).join(" / ");
  if (utm) return `Campaign: ${utm}`;
  if (lead.referrer?.trim()) return lead.referrer.trim();
  return null;
}

function prettyIntent(v: string | null): string | null {
  if (v === "buying") return "Buy a home";
  if (v === "selling") return "Sell a home";
  if (v === "both") return "Buy and sell";
  return v;
}

function prettyTimeframe(v: string | null): string | null {
  if (v === "asap") return "As soon as possible";
  if (v === "3_months") return "In the next 3 months";
  if (v === "6_months") return "In the next 6 months";
  if (v === "exploring") return "Just exploring";
  return v;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
